# Generated by Django 2.0.8 on 2018-09-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180913_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipodedato',
            name='detalle',
            field=models.TextField(blank=True),
        ),
    ]
