# Generated by Django 2.1.1 on 2018-10-12 03:54

from django.db import migrations

def crearTiposDeDato(apps, schema_editor):
	TipoDeDato_model = apps.get_model('api', 'TipoDeDato')
	TipoDeDato_model.objects.bulk_create([
		TipoDeDato_model(nombre='seleccion_unica', detalle=''),
		TipoDeDato_model(nombre='seleccion_multiple', detalle=''),
		TipoDeDato_model(nombre='valor_exacto', detalle=''),
		TipoDeDato_model(nombre='rango', detalle=''),
		TipoDeDato_model(nombre='texto', detalle=''),
		TipoDeDato_model(nombre='tabla_ram', detalle=''),
		TipoDeDato_model(nombre='tabla_mico', detalle=''),
		TipoDeDato_model(nombre='desconocido', detalle=''),
	])

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180924_0049'),
    ]

    operations = [
    	migrations.RunPython(crearTiposDeDato),
    ]
