# Generated by Django 2.1.1 on 2018-10-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181011_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantilla',
            name='descripcion',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
