# Generated by Django 2.0.8 on 2018-10-24 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='plantilla',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Plantilla'),
            preserve_default=False,
        ),
    ]
