# Generated by Django 2.0.8 on 2018-10-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_programa_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seccion',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
