# Generated by Django 2.0.8 on 2018-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181029_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='seccion',
            name='orden',
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_envio_paquete',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_envio_resultados',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='programa',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
