# Generated by Django 2.1.1 on 2018-11-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181031_0852'),
        ('api', '0012_auto_20181030_2219'),
    ]

    operations = [
    ]
